module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      { schema: 'userservice', tableName: 'profile' },
      [
        {
          "id": 2,
          "externalId": "E101",
          "name": "John",
          "firstName": "John",
          "lastName": "Doe",
          "middleName": "A",
          "workEmail": "jdoe@co.com",
          "workPhone": "1234567890",
          "personalPhone": "0987654321",
          "personalEmail": "jdoe@gmail.com",
          "fax": null,
          "gender": "Male",
          "isPerson": true,
          "workAddress": "123 Street",
          "profilePicture": "Picture1.png"
        },
        {
          "id": 3,
          "externalId": "E102",
          "name": "Jane",
          "firstName": "Jane",
          "lastName": "Doe",
          "middleName": "B",
          "workEmail": "jane@co.com",
          "workPhone": "4567890123",
          "personalPhone": "3210987654",
          "personalEmail": "jane@gmail.com",
          "fax": null,
          "gender": "Female",
          "isPerson": true,
          "workAddress": "124 Street",
          "profilePicture": "Picture2.png"
        },
        {
          "id": 4,
          "externalId": "E103",
          "name": "Sam",
          "firstName": "Sam",
          "lastName": "Smith",
          "middleName": "C",
          "workEmail": "sam@co.com",
          "workPhone": "7890123456",
          "personalPhone": "6543219876",
          "personalEmail": "sam@gmail.com",
          "fax": null,
          "gender": "Male",
          "isPerson": true,
          "workAddress": "125 Street",
          "profilePicture": "Picture3.png"
        },
        {
          "id": 5,
          "externalId": "E104",
          "name": "Jake",
          "firstName": "Jake",
          "lastName": "Smith",
          "middleName": "D",
          "workEmail": "jake@co.com",
          "workPhone": "1231231234",
          "personalPhone": "9879879876",
          "personalEmail": "jake@gmail.com",
          "fax": null,
          "gender": "Male",
          "isPerson": true,
          "workAddress": "126 Street",
          "profilePicture": "Picture4.png"
        },
        {
          "id": 6,
          "externalId": "E105",
          "name": "Liam",
          "firstName": "Liam",
          "lastName": "Johnson",
          "middleName": "E",
          "workEmail": "liam@co.com",
          "workPhone": "2342342345",
          "personalPhone": "8768768765",
          "personalEmail": "liam@gmail.com",
          "fax": null,
          "gender": "Male",
          "isPerson": true,
          "workAddress": "127 Street",
          "profilePicture": "Picture5.png"
        },
        {
          "id": 7,
          "externalId": "E106",
          "name": "Emma",
          "firstName": "Emma",
          "lastName": "Williams",
          "middleName": "F",
          "workEmail": "emma@co.com",
          "workPhone": "3453453456",
          "personalPhone": "7657657654",
          "personalEmail": "emma@gmail.com",
          "fax": null,
          "gender": "Female",
          "isPerson": true,
          "workAddress": "128 Street",
          "profilePicture": "Picture6.png"
        },
        {
          "id": 8,
          "externalId": "E107",
          "name": "Olivia",
          "firstName": "Olivia",
          "lastName": "Jones",
          "middleName": "G",
          "workEmail": "olivia@co.com",
          "workPhone": "4564564567",
          "personalPhone": "6546546543",
          "personalEmail": "olivia@gmail.com",
          "fax": null,
          "gender": "Female",
          "isPerson": true,
          "workAddress": "129 Street",
          "profilePicture": "Picture7.png"
        },
        {
          "id": 9,
          "externalId": "E108",
          "name": "Noah",
          "firstName": "Noah",
          "lastName": "Brown",
          "middleName": "H",
          "workEmail": "noah@co.com",
          "workPhone": "5675675678",
          "personalPhone": "5435435432",
          "personalEmail": "noah@gmail.com",
          "fax": null,
          "gender": "Male",
          "isPerson": true,
          "workAddress": "130 Street",
          "profilePicture": "Picture8.png"
        },
        {
          "id": 10,
          "externalId": "E109",
          "name": "Ava",
          "firstName": "Ava",
          "lastName": "Davis",
          "middleName": "I",
          "workEmail": "ava@co.com",
          "workPhone": "6786786789",
          "personalPhone": "4324324321",
          "personalEmail": "ava@gmail.com",
          "fax": null,
          "gender": "Female",
          "isPerson": true,
          "workAddress": "131 Street",
          "profilePicture": "Picture9.png"
        },
        {
          "id": 11,
          "externalId": "E110",
          "name": "Mason",
          "firstName": "Mason",
          "lastName": "Miller",
          "middleName": "J",
          "workEmail": "mason@co.com",
          "workPhone": "7897897890",
          "personalPhone": "3213213210",
          "personalEmail": "mason@gmail.com",
          "fax": null,
          "gender": "Male",
          "isPerson": true,
          "workAddress": "132 Street",
          "profilePicture": "Picture10.png"
        },
        {
          "id": 12,
          "externalId": "E111",
          "name": "Sophia",
          "firstName": "Sophia",
          "lastName": "Taylor",
          "middleName": "K",
          "workEmail": "sophia@co.com",
          "workPhone": "8908908901",
          "personalPhone": "2102102100",
          "personalEmail": "sophia@gmail.com",
          "fax": null,
          "gender": "Female",
          "isPerson": true,
          "workAddress": "133 Street",
          "profilePicture": "Picture11.png"
        },
        {
          "id": 13,
          "externalId": "E112",
          "name": "James",
          "firstName": "James",
          "lastName": "Anderson",
          "middleName": "L",
          "workEmail": "james@co.com",
          "workPhone": "9019019012",
          "personalPhone": "1091091098",
          "personalEmail": "james@gmail.com",
          "fax": null,
          "gender": "Male",
          "isPerson": true,
          "workAddress": "134 Street",
          "profilePicture": "Picture12.png"
        },
        {
          "id": 14,
          "externalId": "E113",
          "name": "Isabella",
          "firstName": "Isabella",
          "lastName": "Thomas",
          "middleName": "M",
          "workEmail": "isabella@co.com",
          "workPhone": "0120120123",
          "personalPhone": "1081081087",
          "personalEmail": "isabella@gmail.com",
          "fax": null,
          "gender": "Female",
          "isPerson": true,
          "workAddress": "135 Street",
          "profilePicture": "Picture13.png"
        }
      ]
      , {});
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete(
      { schema: 'userservice', tableName: 'profile' }, // Specify schema and table
      {}
    );
  }
};
